In [4]:
import numpy as np
from numpy import doc
help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    /home/admin1/.local/lib/python3.8/site-packages/numpy/doc/__init__.py




### Arrays, axises, dimensions

In [5]:
np.array

<function numpy.array>

In [10]:
a = np.array([1,2,3])
print(repr(a))
print(type(a))
print("Axises:", a.ndim)
print("Shape:", a.shape)

array([1, 2, 3])
<class 'numpy.ndarray'>
Axises: 1
Shape: (3,)


In [11]:
[a, 1, 0.1, '2', object(), None]

[array([1, 2, 3]), 1, 0.1, '2', <object at 0x7f1486e4a670>, None]

In [12]:
a.dtype

dtype('int64')

In [15]:
print("Elem's size:", a.itemsize, "bytes")

Elem's size: 8 bytes


In [22]:
b = np.array([[4,5,6], [7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
print("Size:", b.size)
print("Axises:", b.ndim)
print("Shape:", b.shape)

Size: 6
Axises: 2
Shape: (2, 3)


In [24]:
print(repr(b.dtype))
print(b.dtype.name)
print(b.itemsize)
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

dtype('int64')
int64
8
int32
4


### Creating arrays

In [26]:
a = np.arange(15)
print(a)
a = a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
b = np.arange(15,115, 5).reshape(4,-1)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)
b

(4, 5)
2
20
int64


array([[ 15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60],
       [ 65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110]])

In [32]:
a = np.arange(1, 5, 0.5)
print(a)
print(a.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
8


In [33]:
a = np.arange(0, 2, 0.3)
print(a)
print(a.size)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
7


In [34]:
a = np.linspace(0, 6, 20)
print(a)
print(a.size)

[0.         0.31578947 0.63157895 0.94736842 1.26315789 1.57894737
 1.89473684 2.21052632 2.52631579 2.84210526 3.15789474 3.47368421
 3.78947368 4.10526316 4.42105263 4.73684211 5.05263158 5.36842105
 5.68421053 6.        ]
20


In [40]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [41]:
SIZE = 10
SHAPE =(SIZE,)

res = np.zeros(SHAPE)
print(res.dtype)
print(res)

float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
res = np.zeros(SHAPE, dtype=a.dtype)
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
for i in range(SIZE):
    res[i] = a[i] + b[i]
res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [44]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [51]:
SHAPE = (2, 3)
a = np.arange(1,  7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

assert a.shape == b.shape

In [52]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [53]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [57]:
a = np.arange(7)
b = np.arange(9)

try:
    a + b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (7,) (9,) 


### Operations

In [58]:
np.arange(10,20) / np.arange(10)

<ipython-input-58-fe31c18044fc>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.arange(10,20) / np.arange(10)


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [62]:
a = np.arange(10)
print(a)
print("Разница между n и n+1 элементом:")
np.diff(a)

[0 1 2 3 4 5 6 7 8 9]
Разница между n и n+1 элементом:


array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
print(np.diff(a))

[[10 15 20 25]
 [30 35 40 45]]
[[5 5 5]
 [5 5 5]]


In [64]:
a * 3

array([[ 30,  45,  60,  75],
       [ 90, 105, 120, 135]])

In [65]:
np.diff(a * 4)

array([[20, 20, 20],
       [20, 20, 20]])

In [66]:
np.sum(a)

220

In [67]:
np.sum(a * 3)

660

In [68]:
a.ndim

2

In [69]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [74]:
for dim in range(a.ndim):
    print(f"Sum on axis {dim}:", np.sum(a, axis=dim))

Sum on axis 0: [40 50 60 70]
Sum on axis 1: [ 70 150]


In [78]:
for dim in range(a.ndim):
    print(f"Product on axis {dim}:", np.prod(a, axis=dim))

Product on axis 0: [ 300  525  800 1125]
Product on axis 1: [  75000 1890000]


In [80]:
np.prod(a, axis=None) == np.prod(a)

True

In [82]:
a ** 2

array([[ 100,  225,  400,  625],
       [ 900, 1225, 1600, 2025]])

In [83]:
np.sqrt(a)

array([[3.16227766, 3.87298335, 4.47213595, 5.        ],
       [5.47722558, 5.91607978, 6.32455532, 6.70820393]])

In [85]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [84]:
a > 30

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [88]:
b = np.linspace(40, 75, 8, dtype=np.int64).reshape(2, 4)
b

array([[40, 45, 50, 55],
       [60, 65, 70, 75]])

In [89]:
a < b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [98]:
b = np.arange(50, 10, -5).reshape(2,4)
b

array([[50, 45, 40, 35],
       [30, 25, 20, 15]])

In [99]:
a > b

array([[False, False, False, False],
       [False,  True,  True,  True]])

### Data types

In [107]:
print("Numpy приводит элементы к нужному типу:")
print(a.dtype)
print((a / 3).dtype)
print((a > b).dtype)
print((a // b).dtype)
print((a % b).dtype)

Numpy приводит элементы к нужному типу:
int64
float64
bool
int64
int64


### Indexes, slides

In [108]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [109]:
a[8]

512

In [110]:
a[2:5]

array([ 8, 27, 64])

In [111]:
a[7:]

array([343, 512, 729])

In [114]:
print("from 3-rd to 9-th (not included) elem with step 2:")
a[3:9:2]

from 3-rd to 9-th (not included) elem with step 2:


array([ 27, 125, 343])

In [115]:
print("from 3-rd to the last (included!) elem with step 2:")
a[3::2]

from 3-rd to the last (included!) elem with step 2:


array([ 27, 125, 343, 729])

In [118]:
print("from the first to the last (included!) elem with step 3 (every 3-rd elem)")
a[::3]

from the first to the last (included!) elem with step 3 (every 3-rd elem)


array([  0,  27, 216, 729])

In [120]:
print("from the last to the first (included!) elem with step 3")
a[::-3]

from the last to the first (included!) elem with step 3


array([729, 216,  27,   0])

In [121]:
print("reverted order")
a[::-1]

reverted order


array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

### Setting values

In [122]:
a[:9:3] = 123
a

array([123,   1,   8, 123,  64, 125, 123, 343, 512, 729])