In [1]:
import numpy as np
from numpy import doc
help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    c:\users\lpikulev\anaconda3\lib\site-packages\numpy\doc\__init__.py




### Arrays, axises, dimensions

In [2]:
np.array

<function numpy.array>

In [3]:
a = np.array([1,2,3])
print(repr(a))
print(type(a))
print("Axises:", a.ndim)
print("Shape:", a.shape)

array([1, 2, 3])
<class 'numpy.ndarray'>
Axises: 1
Shape: (3,)


In [4]:
[a, 1, 0.1, '2', object(), None]

[array([1, 2, 3]), 1, 0.1, '2', <object at 0x20c1b7c6980>, None]

In [5]:
a.dtype

dtype('int32')

In [6]:
print("Elem's size:", a.itemsize, "bytes")

Elem's size: 4 bytes


In [7]:
b = np.array([[4,5,6], [7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [8]:
print("Size:", b.size)
print("Axises:", b.ndim)
print("Shape:", b.shape)

Size: 6
Axises: 2
Shape: (2, 3)


In [9]:
print(repr(b.dtype))
print(b.dtype.name)
print(b.itemsize)
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

dtype('int32')
int32
4
int32
4


### Creating arrays

In [10]:
a = np.arange(15)
print(a)
a = a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
b = np.arange(15,115, 5).reshape(4,-1)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)
b

(4, 5)
2
20
int32


array([[ 15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60],
       [ 65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110]])

In [12]:
a = np.arange(1, 5, 0.5)
print(a)
print(a.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
8


In [13]:
a = np.arange(0, 2, 0.3)
print(a)
print(a.size)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
7


In [14]:
a = np.linspace(0, 6, 20)
print(a)
print(a.size)

[0.         0.31578947 0.63157895 0.94736842 1.26315789 1.57894737
 1.89473684 2.21052632 2.52631579 2.84210526 3.15789474 3.47368421
 3.78947368 4.10526316 4.42105263 4.73684211 5.05263158 5.36842105
 5.68421053 6.        ]
20


In [15]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [16]:
SIZE = 10
SHAPE =(SIZE,)

res = np.zeros(SHAPE)
print(res.dtype)
print(res)

float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
res = np.zeros(SHAPE, dtype=a.dtype)
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
for i in range(SIZE):
    res[i] = a[i] + b[i]
res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [21]:
SHAPE = (2, 3)
a = np.arange(1,  7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

assert a.shape == b.shape

In [22]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [23]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [24]:
a = np.arange(7)
b = np.arange(9)

try:
    a + b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (7,) (9,) 


### Operations

In [25]:
np.arange(10,20) / np.arange(10)

C:\Users\lpikulev\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [26]:
a = np.arange(10)
print(a)
print("Разница между n и n+1 элементом:")
np.diff(a)

[0 1 2 3 4 5 6 7 8 9]
Разница между n и n+1 элементом:


array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
print(np.diff(a))

[[10 15 20 25]
 [30 35 40 45]]
[[5 5 5]
 [5 5 5]]


In [28]:
a * 3

array([[ 30,  45,  60,  75],
       [ 90, 105, 120, 135]])

In [29]:
np.diff(a * 4)

array([[20, 20, 20],
       [20, 20, 20]])

In [30]:
np.sum(a)

220

In [31]:
np.sum(a * 3)

660

In [32]:
a.ndim

2

In [33]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [34]:
for dim in range(a.ndim):
    print(f"Sum on axis {dim}:", np.sum(a, axis=dim))

Sum on axis 0: [40 50 60 70]
Sum on axis 1: [ 70 150]


In [35]:
for dim in range(a.ndim):
    print(f"Product on axis {dim}:", np.prod(a, axis=dim))

Product on axis 0: [ 300  525  800 1125]
Product on axis 1: [  75000 1890000]


In [36]:
np.prod(a, axis=None) == np.prod(a)

True

In [37]:
a ** 2

array([[ 100,  225,  400,  625],
       [ 900, 1225, 1600, 2025]], dtype=int32)

In [38]:
np.sqrt(a)

array([[3.16227766, 3.87298335, 4.47213595, 5.        ],
       [5.47722558, 5.91607978, 6.32455532, 6.70820393]])

In [39]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [40]:
a > 30

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [41]:
b = np.linspace(40, 75, 8, dtype=np.int64).reshape(2, 4)
b

array([[40, 45, 50, 55],
       [60, 65, 70, 75]], dtype=int64)

In [42]:
a < b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
b = np.arange(50, 10, -5).reshape(2,4)
b

array([[50, 45, 40, 35],
       [30, 25, 20, 15]])

In [44]:
a > b

array([[False, False, False, False],
       [False,  True,  True,  True]])

### Data types

In [45]:
print("Numpy приводит элементы к нужному типу:")
print(a.dtype)
print((a / 3).dtype)
print((a > b).dtype)
print((a // b).dtype)
print((a % b).dtype)

Numpy приводит элементы к нужному типу:
int32
float64
bool
int32
int32


### Indexes, slides

In [46]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [47]:
a[8]

512

In [48]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [49]:
a[7:]

array([343, 512, 729], dtype=int32)

In [50]:
print("from 3-rd to 9-th (not included) elem with step 2:")
a[3:9:2]

from 3-rd to 9-th (not included) elem with step 2:


array([ 27, 125, 343], dtype=int32)

In [51]:
print("from 3-rd to the last (included!) elem with step 2:")
a[3::2]

from 3-rd to the last (included!) elem with step 2:


array([ 27, 125, 343, 729], dtype=int32)

In [52]:
print("from the first to the last (included!) elem with step 3 (every 3-rd elem)")
a[::3]

from the first to the last (included!) elem with step 3 (every 3-rd elem)


array([  0,  27, 216, 729], dtype=int32)

In [53]:
print("from the last to the first (included!) elem with step 3")
a[::-3]

from the last to the first (included!) elem with step 3


array([729, 216,  27,   0], dtype=int32)

In [54]:
print("reverted order")
a[::-1]

reverted order


array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

### Setting values

In [55]:
a[:9:3]

array([  0,  27, 216], dtype=int32)

In [56]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [57]:
a[:9:3]

array([  0,  27, 216], dtype=int32)

### Creating arrays

In [58]:
SHAPE = 5, 4
b = np.arange(20).reshape(SHAPE)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
def f(x, y):
    return 10 * x + y

print(f(3, 4))

34


In [61]:
print("x - horizontal axis, y - vertical axis, cross - f's result")
np.fromfunction(f, SHAPE)

x - horizontal axis, y - vertical axis, cross - f's result


array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [62]:
np.fromfunction(f, (10, 10))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [68]:
# def inc_by_index_1(x):
#     print(type(x))
#     if not (x > 0):
        
#         return x
#     return x + inc_by_index_1(x - 1)

# print(inc_by_index_1(1))
# print(inc_by_index_1(2))
# print(inc_by_index_1(3))

In [69]:
a = np.arange(10, 50, 2).reshape(5, 4)
a

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [71]:
a[4][0]

42

In [72]:
a[4, 0]

42

In [73]:
a[:, 3]

array([16, 24, 32, 40, 48])

In [74]:
a[1:3, :2]

array([[18, 20],
       [26, 28]])

In [78]:
# reflection hor
a[::-1]

array([[42, 44, 46, 48],
       [34, 36, 38, 40],
       [26, 28, 30, 32],
       [18, 20, 22, 24],
       [10, 12, 14, 16]])

In [76]:
# 
a[::-1, ::-1]

array([[48, 46, 44, 42],
       [40, 38, 36, 34],
       [32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10]])

In [79]:
a.transpose()

array([[10, 18, 26, 34, 42],
       [12, 20, 28, 36, 44],
       [14, 22, 30, 38, 46],
       [16, 24, 32, 40, 48]])

In [80]:
a

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [96]:
SHAPE_3D = (2, 4, 6)

a = np.arange(SHAPE_3D[0]*SHAPE_3D[1]*SHAPE_3D[2]).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [97]:
print(a.shape)
print(a.ndim)
print(a.size)

(2, 4, 6)
3
48


In [98]:
print(a[1])
print(a[:, 3])
print(a[:, :, 5])

[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
[[18 19 20 21 22 23]
 [42 43 44 45 46 47]]
[[ 5 11 17 23]
 [29 35 41 47]]


In [99]:
a[1, 3, 5]

47

In [100]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [101]:
a ** 5

array([[[        0,         1,        32,       243,      1024,
              3125],
        [     7776,     16807,     32768,     59049,    100000,
            161051],
        [   248832,    371293,    537824,    759375,   1048576,
           1419857],
        [  1889568,   2476099,   3200000,   4084101,   5153632,
           6436343]],

       [[  7962624,   9765625,  11881376,  14348907,  17210368,
          20511149],
        [ 24300000,  28629151,  33554432,  39135393,  45435424,
          52521875],
        [ 60466176,  69343957,  79235168,  90224199, 102400000,
         115856201],
        [130691232, 147008443, 164916224, 184528125, 205962976,
         229345007]]], dtype=int32)

In [102]:
SHAPE_5D = tuple(range(2, 7))
SHAPE_5D

(2, 3, 4, 5, 6)

In [104]:
d = np.empty(SHAPE_5D, dtype=np.int16)
d

array([[[[[ -5936,   7121,    524,      0,  -7536,   6812],
          [   524,      0, -25080,   7867,    524,      0],
          [ 10888,   7867,    524,      0,  -8056,   7866],
          [   524,      0,  -5112,   7866,    524,      0],
          [-28472,   7866,    524,      0, -28536,   7866]],

         [[   524,      0, -26808,   7866,    524,      0],
          [-25080,   7866,    524,      0, -25976,   7866],
          [   524,      0, -25016,   7866,    524,      0],
          [-24760,   7866,    524,      0, -25464,   7866],
          [   524,      0, -25144,   7866,    524,      0]],

         [[-26040,   7866,    524,      0, -28024,   7866],
          [   524,      0, -25656,   7866,    524,      0],
          [-26232,   7866,    524,      0,  30088,   7917],
          [   524,      0,  29768,   7917,    524,      0],
          [ 30216,   7917,    524,      0,  31432,   7917]],

         [[   524,      0,  30600,   7917,    524,      0],
          [ 31176,   7917,    524,

In [105]:
d[1, :, :, :, 5]

array([[[7864,    0, 7864,    0, 8006],
        [   0, 7899,    0, 7899,    0],
        [7908,    0, 7908,    0, 7863],
        [   0, 7863,    0, 7863,    0]],

       [[7863,    0, 7863,    0, 7863],
        [   0, 7863,    0, 7863,    0],
        [7863,    0, 7863,    0, 7862],
        [   0, 7862,    0, 7862,    0]],

       [[7862,    0, 7862,    0, 7571],
        [   0, 7571,    0, 7911,    0],
        [7918,    0, 7919,    0, 7861],
        [   0, 7861,    0, 7860,    0]]], dtype=int16)

In [106]:
d[1, ..., 5]

array([[[7864,    0, 7864,    0, 8006],
        [   0, 7899,    0, 7899,    0],
        [7908,    0, 7908,    0, 7863],
        [   0, 7863,    0, 7863,    0]],

       [[7863,    0, 7863,    0, 7863],
        [   0, 7863,    0, 7863,    0],
        [7863,    0, 7863,    0, 7862],
        [   0, 7862,    0, 7862,    0]],

       [[7862,    0, 7862,    0, 7571],
        [   0, 7571,    0, 7911,    0],
        [7918,    0, 7919,    0, 7861],
        [   0, 7861,    0, 7860,    0]]], dtype=int16)

In [107]:
print(d.shape)
print(d[1, ..., 5].shape)

(2, 3, 4, 5, 6)
(3, 4, 5)


In [108]:
d[..., 4, 5]

array([[[7866,    0, 7917,    0],
        [7866,    0, 7917,    0],
        [7865,    0, 7918,    0]],

       [[8006,    0, 7863,    0],
        [7863,    0, 7862,    0],
        [7571,    0, 7861,    0]]], dtype=int16)

In [110]:
a = np.arange(18).reshape((2,3,3))
print(np.linalg.det(a))

[0. 0.]
